/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package airlineReservationSystem;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.web.bind.annotation.CrossOrigin;

@SpringBootApplication
public class Library {

    
    public static void main(String[] args)
    {
    	SpringApplication.run(Library.class, args);
    }
}
